name: DOS4GM_PIPELINE

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: USE NODEJS 18.12.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.0

    - name: CACHE NPM DEPENDENCIES
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: INSTALL PROJECT DEPENDENCIES
      working-directory: ./src
      run: npm ci --ignore-scripts ./src
    
    - name: TEST APPLICATION
      working-directory: ./src
      run: npm run test
    
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: TEST SECRETS
      working-directory: ./src
      run: echo ${{secrets.DOCKERHUB_USER}} && echo ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: DOCKER HUB LOGIN
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: BUILD IMAGE
      working-directory: ./src
      run: docker build -t hefantini/dos4gm .
      
    - name: DOCKER HUB PUSH
      working-directory: ./src
      run: docker push hefantni/dos4gm:latest      
