name: DOS4GM_PIPELINE

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  prepare:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: USE NODEJS 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
        
      - name: CACHE NPM DEPENDENCIES
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-        
              
      - name: INSTALL PROJECT DEPEDENCIES
        working-directory: ./src
        run: npm ci --ignore-scripts ./src
        
  test:
    needs: prepare
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: TEST APPLICATION
      working-directory: ./src
      run: npm run test
    
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: BUILD IMAGE
      working-directory: ./src
      run: docker build -t hefantini/dos4gm .
      
  push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3     
    
    - name: DOCKER HUB LOGIN
      run: docker login -u ${{ vars.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
    - name: DOCKER HUB PUSH
      working-directory: ./src
      run: docker push hefantni/dos4gm:latest
      
